//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCThreading.Libraries.DataAccessManager.DataModels.BasicModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BettorROVReportBreaks
    {
        public int BettorId { get; set; }
        public int ROVReportId { get; set; }
        public Nullable<decimal> ReportedAmount { get; set; }
        public System.DateTime BreakDate { get; set; }
    
        public virtual Bettors Bettors { get; set; }
        public virtual ROVReports ROVReports { get; set; }
    }
}
