//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCThreading.Libraries.DataAccessManager.DataModels.BasicModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLEToteEntities : DbContext
    {
        public PLEToteEntities()
            : base("name=PLEToteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BettorROVReportBreaks> BettorROVReportBreaks { get; set; }
        public virtual DbSet<Bettors> Bettors { get; set; }
        public virtual DbSet<BettorTickets> BettorTickets { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<ROVReports> ROVReports { get; set; }
        public virtual DbSet<Taxes> Taxes { get; set; }
        public virtual DbSet<TicketProperties> TicketProperties { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<TicketWager> TicketWager { get; set; }
        public virtual DbSet<Totes> Totes { get; set; }
        public virtual DbSet<vReportTaxes> vReportTaxes { get; set; }
        public virtual DbSet<vReportTickets> vReportTickets { get; set; }
        public virtual DbSet<vTickets> vTickets { get; set; }
    }
}
