//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCThreading.Libraries.DataAccessManager.DataModels.BasicModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROVReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROVReports()
        {
            this.BettorROVReportBreaks = new HashSet<BettorROVReportBreaks>();
        }
    
        public int ROVReportId { get; set; }
        public string ReportDesc { get; set; }
        public string OutputFormat { get; set; }
        public bool CutEnabled { get; set; }
        public bool IncludeSold { get; set; }
        public Nullable<decimal> AmountSoldLimit { get; set; }
        public bool IncludeCashed { get; set; }
        public Nullable<decimal> AmountCashedLimit { get; set; }
        public bool IncludeIndividualTickets { get; set; }
        public bool IncludeAccumulativeTickets { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BettorROVReportBreaks> BettorROVReportBreaks { get; set; }
    }
}
