//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCThreading.Libraries.DataAccessManager.DataModels.BasicModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketWager
    {
        public int TicketWagerId { get; set; }
        public long TicketNumber { get; set; }
        public int ToteId { get; set; }
        public System.DateTime EventDate { get; set; }
        public string WagerHeader { get; set; }
        public string WagerDetail { get; set; }
        public string WagerExtraInfo { get; set; }
        public string WagerSource { get; set; }
    
        public virtual Tickets Tickets { get; set; }
    }
}
