//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCThreading.Libraries.DataAccessManager.DataModels.BasicModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketProperties
    {
        public int ToteId { get; set; }
        public long TicketNumber { get; set; }
        public string Property { get; set; }
        public System.DateTime RegisteredOn { get; set; }
        public string PropertyValue { get; set; }
    
        public virtual Tickets Tickets { get; set; }
    }
}
