//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCThreading.Libraries.DataAccessManager.DataModels.BasicModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReportTickets
    {
        public long TicketNumber { get; set; }
        public int LocationId { get; set; }
        public int ToteId { get; set; }
        public string TerminalSold { get; set; }
        public string TerminalCashed { get; set; }
        public string LocationName { get; set; }
        public string TicketType { get; set; }
        public string ETSN { get; set; }
        public System.DateTime DateSold { get; set; }
        public Nullable<System.DateTime> DateSoldOp { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<System.DateTime> DatePaidOp { get; set; }
        public Nullable<System.DateTime> DateSettled { get; set; }
        public Nullable<System.DateTime> DateSettledOp { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public Nullable<System.DateTime> DateExpiredOp { get; set; }
        public Nullable<System.DateTime> DateVoided { get; set; }
        public Nullable<System.DateTime> DateVoidedOp { get; set; }
        public string TicketDescription { get; set; }
        public Nullable<int> TillSessionSold { get; set; }
        public Nullable<int> TillSessionCashed { get; set; }
        public Nullable<decimal> Estrategia { get; set; }
        public byte TicketStatus { get; set; }
        public decimal WriteTake { get; set; }
        public Nullable<decimal> WriteTake_Es { get; set; }
        public Nullable<decimal> Refund { get; set; }
        public Nullable<decimal> Refund_Es { get; set; }
        public Nullable<decimal> CreditsRefund { get; set; }
        public Nullable<decimal> CreditsRefund_Es { get; set; }
        public Nullable<decimal> Win { get; set; }
        public Nullable<decimal> Win_Es { get; set; }
        public Nullable<decimal> CreditsWin { get; set; }
        public Nullable<decimal> CreditsWin_Es { get; set; }
        public Nullable<decimal> Payout { get; set; }
        public Nullable<decimal> Payout_Es { get; set; }
        public Nullable<decimal> RefundUnpaid { get; set; }
        public Nullable<decimal> RefundUnpaid_Es { get; set; }
        public Nullable<decimal> CreditsRefundUnpaid { get; set; }
        public Nullable<decimal> CreditsRefundUnpaid_Es { get; set; }
        public Nullable<decimal> WinUnpaid { get; set; }
        public Nullable<decimal> WinUnpaid_Es { get; set; }
        public Nullable<decimal> CreditsWinUnpaid { get; set; }
        public Nullable<decimal> CreditsWinUnpaid_Es { get; set; }
        public Nullable<decimal> PayoutUnpaid { get; set; }
        public Nullable<decimal> PayoutUnpaid_Es { get; set; }
        public Nullable<decimal> Payoff { get; set; }
        public Nullable<decimal> Payoff_Es { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public decimal SoldValue { get; set; }
        public Nullable<decimal> SoldValue_ES { get; set; }
        public Nullable<decimal> CashedValue { get; set; }
        public Nullable<decimal> CashedValue_Es { get; set; }
        public Nullable<decimal> SettledValue { get; set; }
        public Nullable<decimal> SettledValue_Es { get; set; }
        public decimal RefundValue { get; set; }
        public Nullable<decimal> RefundValue_Es { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> TaxBet { get; set; }
        public Nullable<decimal> TaxBet_Es { get; set; }
        public Nullable<decimal> TaxWin { get; set; }
        public Nullable<decimal> TaxWin_Es { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<int> WinTaxId { get; set; }
        public Nullable<int> BetTaxId { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<bool> IsDraw { get; set; }
        public string DetalleApuesta { get; set; }
        public string FolioVenta { get; set; }
        public string FolioPago { get; set; }
    }
}
