//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCThreading.Libraries.DataAccessManager.DataModels.BasicModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReportTaxes
    {
        public long TicketNumber { get; set; }
        public string TicketType { get; set; }
        public Nullable<int> TaxId { get; set; }
        public string TaxName { get; set; }
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public int ToteId { get; set; }
        public byte TicketStatus { get; set; }
        public string ETSN { get; set; }
        public string TerminalCashed { get; set; }
        public Nullable<System.DateTime> CashedDate { get; set; }
        public Nullable<System.DateTime> CashedDateOp { get; set; }
        public decimal SoldValue { get; set; }
        public Nullable<decimal> SoldValue_Es { get; set; }
        public Nullable<decimal> TicketWin { get; set; }
        public Nullable<decimal> TicketWin_Es { get; set; }
        public Nullable<decimal> PayoutValue { get; set; }
        public Nullable<decimal> PayoutValue_Es { get; set; }
        public Nullable<decimal> RefundValue { get; set; }
        public Nullable<decimal> RefundValue_Es { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> TaxValue { get; set; }
        public Nullable<decimal> TaxValue_Es { get; set; }
        public decimal ExchangeRate { get; set; }
        public Nullable<decimal> Estrategia { get; set; }
    }
}
