//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCThreading.Libraries.DataAccessManager.DataModels.BasicModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTickets
    {
        public long TicketNumber { get; set; }
        public int LocationId { get; set; }
        public int ToteId { get; set; }
        public string ETSN { get; set; }
        public string TicketType { get; set; }
        public byte TicketStatus { get; set; }
        public System.DateTime SoldDate { get; set; }
        public Nullable<System.DateTime> SoldOpDate { get; set; }
        public Nullable<System.DateTime> SettledDate { get; set; }
        public Nullable<System.DateTime> SettledOpDate { get; set; }
        public Nullable<System.DateTime> CashedDate { get; set; }
        public Nullable<System.DateTime> CashedOpDate { get; set; }
        public Nullable<System.DateTime> VoidedDate { get; set; }
        public Nullable<System.DateTime> VoidedOpDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<System.DateTime> ExpiredOpDate { get; set; }
        public Nullable<int> SoldTillSessionId { get; set; }
        public decimal SoldValue { get; set; }
        public Nullable<decimal> SoldValue_Es { get; set; }
        public Nullable<decimal> CommissionValue { get; set; }
        public Nullable<decimal> BetTaxRate { get; set; }
        public Nullable<decimal> BetTaxValue { get; set; }
        public Nullable<decimal> BetTaxValue_Es { get; set; }
        public Nullable<int> CashedTillSessionId { get; set; }
        public Nullable<decimal> SettledValue { get; set; }
        public Nullable<decimal> SettledValue_Es { get; set; }
        public Nullable<decimal> RefundValue { get; set; }
        public Nullable<decimal> WinTaxRate { get; set; }
        public string WinTaxType { get; set; }
        public Nullable<decimal> WinTaxValue { get; set; }
        public Nullable<decimal> WinTaxValue_Es { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string SoldCashier { get; set; }
        public string SoldTerminal { get; set; }
        public string CashedCashier { get; set; }
        public string CashedTerminal { get; set; }
        public Nullable<decimal> InfraestructureUse { get; set; }
        public Nullable<bool> IsDraw { get; set; }
        public string WagerType { get; set; }
        public string FolioVenta { get; set; }
        public string FolioPago { get; set; }
    }
}
